modLoader="javafml"
loaderVersion="[31,)" #forge version dep
issueTrackerURL="https://github.com/iChun/BeeBarker/issues"

[[mods]]
    modId="beebarker"
    version="${file.jarVersion}" #mandatory
    displayName="Bee Barker"
    displayURL="https://ichun.me/mods/bee-barker/"
    authors="iChun"
    description='''
    "Oh yeah, what are you gonna do? Release the dogs? Or the bees? Or the dogs with bees in their mouth and when they bark they shoot bees at you?" #TheSimpsonsDidItFirst
    '''

[[dependencies.beebarker]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.beebarker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,1.16)"
    ordering="NONE"
    side="BOTH"
